### ISSUE TITLE
如何将Let's Encrypt更换为云厂商内自身免费SSL证书

### ISSUE THREAD

**Issue by ReyRen** [expoli/start-bolo-with-docker-compose#16]
问题：使用docker-compose.yml文件中默认的SSL认证方式会出现"您的连接不是私密连接"的警告。
希望可以更换为比如阿里云提供的免费SSL证书方式

谢谢

**Comment by expoli** [comment]
这个默认是会自动申请的，可以尝试删除对应的证书文件夹，并检查80，443是否能够正常访问

**Comment by expoli** [comment]
https://github.com/expoli/start-bolo-with-docker-compose/releases/tag/v1.4

1.4 版本也可尝试一些，具体配置方式类似，不过使用的是nginx 作为web服务器

**Comment by expoli** [comment]
1.3 版本支持自定义证书、使用nginx 作为web 服务器
替换相应占用文件、并同步修改nginx配置文件即可
![image](https://user-images.githubusercontent.com/31023767/117262430-d4daf400-ae83-11eb-9a70-f634f18f883e.png)

**Comment by ReyRen** [comment]
@expoli 使用了v1.3版本，更换成功。感谢，closed！
